### ISSUE TITLE
Golang release API

### ISSUE THREAD

**Issue by solderjs** [webinstall/packages#1]
There is a release API, it's just not as well advertised. Gotta read the docs of the package rather than the web page:

<https://golang.org/dl/?mode=json&include=all>

- https://github.com/golang/go/issues/34864
- https://pkg.go.dev/golang.org/x/website/internal/dl?tab=doc
- https://golang.org/dl/?mode=json&include=all
- https://golang.org/dl/?mode=html

**Comment by creedasaurus** [comment]
*Reads a little Go from their download package... immediately misses Go*
ʕ •ᴥ•ʔ

**Comment by solderjs** [comment]
I started on this a bit ago. Were you about to start on it?

**Comment by solderjs** [comment]
You could take flutter and I could take gitea.

**Comment by solderjs** [comment]
Woo hoo!

- https://webinstall.dev/api/releases/golang@latest.tab?limit=25&pretty=true
