### ISSUE TITLE
Request for caddy

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/packages#10]
Can I get a caddy installer?

**Comment by solderjs** [comment]
Should be nearly identical to `rg` since it uses github releases and is a single binary:

https://github.com/webinstall/packages/blob/master/rg/rg.bash

Want to give it a try? Or maybe ask the Caddy team for any special considerations?

**Comment by solderjs** [comment]
See also https://github.com/webinstall/packages#creating-an-installer

**Comment by ryanburnette** [comment]
Sure I’ll do it.
