### ISSUE TITLE
[Bug] Move `chmod` to a different function

### ISSUE THREAD

**Issue by coolaj86** [webinstall/packages#100]
# 1. Move a line from the wrong place to the right place

Currently `chmod a+x "$pkg_src_cmd"` exists at [_webi/template.sh#L229](https://github.com/webinstall/packages/blob/master/_webi/template.sh#L229), inside of `webi_install`.

However, it should be moved to just after the call to `webi_install` at [_webi/template.sh#L323](https://github.com/webinstall/packages/blob/master/_webi/template.sh#L323)

# 2. Add another command

Also, we should add a `chmod a+x "$pkg_src"` for good measure.

# 3. Double check

The prior instance of the command should be removed.

The new section should look like this:

```bash
       [ -n "$(command -v pkg_install)" ] && pkg_install || webi_install
        chmod a+x "$pkg_src"
        chmod a+x "$pkg_src_cmd"
```

Blocking #87 and #53

# Skills Required

Know how to
- `git clone`
- Navigate files and folders
- Use a text editor

**Comment by schmelto** [comment]
would like to work on this issue
