### ISSUE TITLE
Maybe install path should be in output, and how about a path warning?

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/packages#14]
I had occasion to install caddy on a server where I had already installed it previously. When I installed again with webi, it did everything it was supposed to, but the old caddy was the one I stll got as shown by `which caddy`.

The installer output looked something like this

```
...
caddy may conflict with /root/bin/caddy
caddy install
```

Maybe the install message could be something like

```
caddy installed to ~/.local/bin/caddy
WARNING: ~/.local/bin/caddy may not be in $PATH
```

Just brain storming here.

**Comment by solderjs** [comment]
Agreed that the PATH management, and multiple versions should be tracked better.

TODO, help wanted.

**Comment by solderjs** [comment]
This is really an issue for `pathman`

**Comment by ryanburnette** [comment]
Agree

**Comment by solderjs** [comment]
Re-opening because I had a genius idea:

```bash
webi_path_add() {
    pathman add $pkg_dst_bin 2>&1 | grep "export" > $WEBI_TEMP/.PATHS
}
```

And then at the end, just before `rm -rf $WEBI_TEMP` and the `done_message`:

```bash
    cat $WEBI_TEMP/.PATHS
```

**Comment by solderjs** [comment]
This lead me down such a wild goose chase.

I always forget that `echo "" | grep x > blah` will trigger `set -e` to fail. Gotta do `echo "" | grep x > blah || true`.
