### ISSUE TITLE
Request for gitea installer

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/packages#21]
I could use a gitea installer.

**Comment by solderjs** [comment]
https://github.com/webinstall/packages/issues/19

Uses Github Releases:
- https://github.com/webinstall/packages/blob/master/ripgrep/releases.js

Should be nearly identical to either caddy (single binary, no subdirectory): 
- https://github.com/webinstall/packages/blob/master/caddy/install.bash

Or to ripgrep (single binary, with subdirectory):
- https://github.com/webinstall/packages/blob/master/ripgrep/install.bash

**Comment by solderjs** [comment]
You can do this.

**Comment by ryanburnette** [comment]
*can* ... but will i?

**Comment by ryanburnette** [comment]
#25
