### ISSUE TITLE
wanted most recent stable release of caddy, but got beta

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/packages#26]
I installed Caddy today. I wanted the most recent stable release, `2.0.0`, but I got `2.1.0-beta1`.

<img width="991" alt="Screen Shot 2020-06-08 at 4 38 23 PM" src="https://user-images.githubusercontent.com/2252601/84078193-7d4bb400-a9a6-11ea-8f9d-bbb82823bd5f.png">

**Comment by solderjs** [comment]
Should we make the default tag `@stable` rather than `@latest`?

I can see that it is marked as a `pre-release`, so I agree it shouldn't have shown up in the list. Just not sure how to handle it in a generic way?

- https://github.com/caddyserver/caddy/releases (marked as pre-release)

**Comment by ryanburnette** [comment]
Here's the logic I like... in the context of this issue.

https://webinstall.dev/[package]@stable -> latest stable release (caddy 2.0.0)
https://webinstall.dev/[package]@latest -> latest release (caddy 2.1.0-beta1)

https://webinstall.dev/[package] (defaults to @stable)

**Comment by solderjs** [comment]
This should be fixed.

- `''` => `stable`
- `latest` => `stable`
