### ISSUE TITLE
problem with rg installer

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/packages#31]
```
❯ webi rg
Downloading rg to /Users/ryan/Downloads/ripgrep-12.1.1-x86_64-apple-darwin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   652  100   652    0     0   3243      0 --:--:-- --:--:-- --:--:--  3243
100 1842k  100 1842k    0     0  3379k      0 --:--:-- --:--:-- --:--:-- 3379k
Extracting /Users/ryan/Downloads/ripgrep-12.1.1-x86_64-apple-darwin.tar.gz
Installing to /Users/ryan/.local/xbin/rg-12.1.1
rm: /Users/ryan/.local/bin/rg: No such file or directory
```

**Comment by solderjs** [comment]
I had switched to using `-L` to test for symlink and then switched

- from `rm -rf` to `rm -f` when the file IS a symlink
- from `rm -rf` to `rm -rf -i` when the file is NOT a symlink

I expected the behavior to be

1. ignore the doesn't exist error (as `-f` does)
2. ask for permission to delete if it does exist

However, it got weird. So I added a second check for if the thing `-e` exists and now it seems to work again.

Perhaps `rm -i` is not very portable between BSD and GNU or perhaps I just misunderstood. Not sure why it works now... but it does.
