### ISSUE TITLE
problem with Hugo installer

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/packages#37]
Installed hugo on my 64-bit darwin os, but got 32-bit binary.

```bash
❯ webi hugo
Found /Users/ryanburnette/Downloads/hugo_0.64.1_macOS-32bit.tar.gz
Extracting /Users/ryanburnette/Downloads/hugo_0.64.1_macOS-32bit.tar.gz
Installing to /Users/ryanburnette/.local/xbin/hugo-v0.64.1
Checking permission to execute 'hugo' on macOS 11+
Installed 'hugo' v0.64.1 as /Users/ryan/.local/bin/hugo
```

I also expected 0.73, but got 0.64.

**Comment by solderjs** [comment]
I’ll probably have to match on “64\W?bit” and 32bit, and I’ll have to have a special case for Hugo since it’s versions reach all the way to 64.

Dang it’s hard to match arbitrary strings to a cpu architecture!

**Comment by solderjs** [comment]
Fixed https://github.com/webinstall/packages/commit/debcee7e199579466159d9e4fc3b0038ae5f0d20

That's slightly too loose at present as it will also match `.64.` as amd64... but there's just so many ways that people do that. I need to get a list of samples from all supported installers and see what will break if I change that (hopefully nothing) and then just add exceptions into the individual files in the future.
