### ISSUE TITLE
WSL presents an interesting situation

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/packages#39]
WSL presents an interesting situation

I tried installing Node, but I get node.exe

```bash
ryan@RYAN-WIN10:~$ webi node@lts
Downloading node to /home/ryan/Downloads/node-v12.18.2-win-x64.zip
/home/ryan/Downloads/node-v12 100%[=================================================>]  17.87M  45.3MB/s    in 0.4s
Extracting /home/ryan/Downloads/node-v12.18.2-win-x64.zip
Installing to /home/ryan/.local/opt/node-v12.18.2/bin/node
mv: cannot move './node-v12.18.2-win-x64' to '/home/ryan/.local/opt/node-v12.18.2/node-v12.18.2-win-x64': Directory not empty
node@lts-bootstrap.sh: line 311: /home/ryan/.local/opt/node-v12.18.2/bin/node: No such file or directory
```

And `node.exe` is no good in this environment.

**Comment by solderjs** [comment]
I thought I had fixed this. The user agent string for WSL is “Microsoft Linux”, hence it matches for Windows before it matches for Linux.

Let’s test this together tonight.

**Comment by ryanburnette** [comment]
I can test this on or after July 21.

**Comment by solderjs** [comment]
Fixed in production via `hotfix`.

Needs your review on https://github.com/webinstall/packages/pull/45 to merge into `master` @ryanburnette
