### ISSUE TITLE
One weird trick to get `sudo` on Windows 10... you'll never eat bananas again!

### ISSUE THREAD

**Issue by solderjs** [webinstall/packages#42]
Check this out!!

https://stackoverflow.com/a/40321310/151312

I definitely want to add that to `webi`.

@ryanburnette This brings up the issue that we do need a way to have non-mac/non-linux (meaning Windows 10 only) installer pages.

**Comment by solderjs** [comment]
Hmm... after reading further I'm not sure if that's actually a great solution.

Here's another idea:

- http://code.kliu.org/misc/elevate/

The problem there being:
- no https for downloads (can't use it in accordance with our security practices)
- requires 7z (because 1337 h4x0rz...)

**Comment by solderjs** [comment]
Okay, I tried https://stackoverflow.com/a/55643173/151312, and it worked, although with a UAC prompt rather than a password prompt.

`sudo.cmd`:

```cmd
@echo off
powershell -Command "Start-Process cmd -Verb RunAs -ArgumentList '/c cd /d %CD% && %*'"
@echo on
```

It also opens up a new cmd.exe window and this disappears.

Though... it seems to work.

```cmd
sudo.cmd dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
```

**Comment by coolaj86** [comment]
@ajaxStardust
1. You're welcome
2. No, that comment doesn't belong there. I can't move it, but if I could, I'd put it here (<https://github.com/webinstall/webi-installers/issues/42>).
3. I'm the core maintainer, but there have been many installer contributions from others \
  (and these are primarily just installers - I didn't create most of the tools)

Re: https://github.com/webinstall/webi-installers/issues/699#issuecomment-2106268767
