### ISSUE TITLE
Update node/install.bat to split commas into variables

### ISSUE THREAD

**Issue by solderjs** [webinstall/packages#5]
Three things to do:

1. Fetch a single line of CSV with this exact URL:

https://webinstall.dev/api/releases/node@v12.csv?os=win&arch=amd64&channel=stable&ext=zip&limit=1

Which looks like this:

```
12.16.3,lts,stable,2020-04-28,windows,amd64,zip,-,https://nodejs.org/dist/v12.16.3/node-v12.16.3-windows-x64.zip
```

2 . Split that string into variables

  - version
  - pkg_url
  - pkg_file
  - pkg_dir
  - os
  - arch

3. Update this batch script to use those variables

- https://github.com/webinstall/packages/blob/master/node/node.bat

I also need to know the variable for the OS and ARCH.

I think `%PROCESSOR_ARCHITECTURE%` is the best / most reliable for ARCH (i.e. `AMD64`)?

Notes

You can use PowerShell commands from Batch, but I think it has to be batch and be able to run in cmd.exe because by default windows won't allow you to run PS1 scripts.

**Comment by cwadrupldijjit** [comment]
I've been keeping this up so that I won't forget it.  I can't boast much experience with batch scripts, but I could have the determination to figure it out...

... which I think I have!

I was curious how to do this myself and though I'm not sure that my solution is the best one, I at least believe that it could work the way you need it to.  The only thing is that I'm not sure how to hook it into the batch script (which seems to be found at https://github.com/webinstall/packages/blob/master/node/install.bat).

Where does the comma-separated param string come from?  As soon as I have that, then I should be able to throw that into the file.  I'm also assuming that you'd want to have the variables like you mentioned replace the hard-coded values in the file, right?

I also have found a way to get the version of Windows, but I'm interested in knowing what you're looking for.  The result of my solution comes out looking like this:
```
Microsoft Windows [Version 10.0.18363.815]
```

Is that sufficient?

**Comment by solderjs** [comment]
Take a look at this:
https://github.com/webinstall/packages/pull/17

The CSV is from the URL mentioned above (and shown in that example).

I think that what you found for the Windows version is better than what's currently there.

See also:
- https://github.com/webinstall/packages/blob/master/webi/template.bash
- https://github.com/webinstall/packages/blob/master/webi/bootstrap.bash

The idea is that when you `curl https://webinstall.dev/node | bash` you'll get a `bash` or `bat` `bootstrap` that copies a helper script and then fetches the `template` + `install` concatenation so that there's a minimal amount of work in creating new installers.

**Comment by solderjs** [comment]
@cwadrupldijjit I completely and totally overhauled the entire system.

Having done a half-dozen bash scripts, I feel like I've identified the unique parts well enough to port it over to bash.

Would you still like to help? Could we get on a call?

> This is the bash template (needs to be ported to batch):

- https://github.com/webinstall/packages/blob/master/_webi/template.sh

> These are the two bash scripts that serve as working examples for what to do in bash to complete the template:

- https://github.com/webinstall/packages/blob/master/node/install.sh
- https://github.com/webinstall/packages/blob/master/caddy/install.sh

> This is where the template is rendered for bash (and a batch function should be added):

- https://github.com/webinstall/packages/blob/master/_webi/releases.js#L16

> And you run this to test it:

```bash
node _webi/test.js ./node
cmd.exe install-node.bat
```

> And here's a partial PR that will become a basis for bootstrap.bat:

- https://github.com/webinstall/packages/pull/17/files

**Comment by cwadrupldijjit** [comment]
I'm not opposed to helping out. When I was looking at the PR you mentioned, it looked like it was doing the same thing as I had done, but might've been more robust. I could take a look at the new scripts to port it over to batch if you want. I might even be up for a call today.

**Comment by jkunkee** [comment]
CMD scripting is quite arcane, and getting something complex to work can be immensely satisfying. (NSIS installer script is even more arcane and similarly satisfying.)

If you can avoid it, though, I recommend doing so.

Given that PowerShell's ExecutionPolicy only applies to script files and not snippets of script, we can dodge CMD entirely with he following:

    powershell "Invoke-Expression (Invoke-WebRequest http://localhost:3000/packages/foo/install.ps1).Content"

This works even with ExecutionPolicy set to Restricted.

(Terrible! I hear you say. Yup, ExecutionPolicy is only useful in a security sense when paired with Constrained Language Mode. The default config just makes social engineering a little harder.)

As for detecting the CPU architecture, you'll want to check the docs I linked in #17 for what vars to check in what order. (And remember that arm64 has x86 emulation.)

**Comment by solderjs** [comment]
Much progress made:
https://github.com/webinstall/packages/pull/35/files

**Comment by solderjs** [comment]
This has since morphed into a different problem/solution set. Closing.
