### ISSUE TITLE
Add `sd`

### ISSUE THREAD

**Issue by coolaj86** [webinstall/packages#53]
# Add sd

We want to add `sd` because it works consistently across Windows, Mac, and Linux.

(`sed` is not as easy to get on Windows, and works differently between GNU and BSD builds).

This could be as simple as copying `_example` (or `bat` or `rg`) and changing a few things.

# How to create a webi installer

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, `tar`, `unzip`, variables)

## Steps

1. Clone and setup the webi packages repo
    ```bash
    git clone git@github.com:webinstall/packages.git
    pushd packages/
    npm install
    ```
2. Copy the example template and update with info from Official Releases: https://github.com/chmln/sd/releases
    ```bash
    rsync -av _example/ sd/
    ```
    - [ ] update `sd/release.js` to use the official repo
    - Learn how `sd` unpacks (i.e. as a single file? as a .tar.gz? as a .tar.gz with a folder named sd?)
    - [ ] find and replace to change the name
      - [ ] update `sd/install.sh` (see `bat` and `jq` as examples)
      - [ ] update `sd/install.ps1` (see `bat` and `jq` as examples)
4. Needs an updated tagline and cheat sheet
    - [ ] update `sd/README.md`
        - [ ] official URL
        - [ ] tagline
        - [ ] Switch versions
        - [ ] description / summary
        - [ ] General pointers on usage (and differences from `sed`)

It's also okay to have multiple people work on part of this (i.e. the Cheat Sheet can be done independently from the `install.sh`)

**Comment by avats-dev** [comment]
**Hey @solderjs , I know command line but I don't know what I need to do here. Guide me.**
> I would love to contribute.

**Comment by solderjs** [comment]
I’d say 

- use the rg and jq installers https://webinstall.dev
-  clone the repo and take a look at `rg` And `jq`
- then ask me specific questions about the above checklist

Do you already use `sd`?

**Comment by solderjs** [comment]
@avats-dev Does that give you a good place to start?

**Comment by solderjs** [comment]
@avats-dev I'm opening this back up for someone else since I didn't hear back from you.

**Comment by avats-dev** [comment]
@solderjs, Sorry I couldn't understand what I needed to do and also I am somewhat busy with other things for now, so let someone else do this. I'll try again after sometime if it would still be open. Thanks btw :+1:

**Comment by chetak123** [comment]
I would like to work on this issue

**Comment by solderjs** [comment]
@chetak123 Awesome. Take a look through the video and the steps above and let me know if you have any questions.

Have you used `sd` before? Or `sed`?

**Comment by chetak123** [comment]
I have used sed a few times, written some basic bash scripts but never used sd

**Comment by solderjs** [comment]
@chetak123 Any update?

**Comment by chetak123** [comment]
i installed the webinstall then node used myip , now trying to understand workflow , but i am not able to understand how sd is installed (used tree command on sd-0.7.6.tar.gz but didn't find any clear executable with which it can be installed)

**Comment by solderjs** [comment]
`sd-0.7.6.tar.gz` is not the right file. Follow the instructions in up to the point of modifying `releases.js` and get the file that `node _webi/test.js sd/` directs you to.

**Comment by chetak123** [comment]
First it was showing this error.
Thanks for using webi to install 'sd' on 'linux-5.4.0-42-generic/x64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

Found /home/ayushman/Downloads/sd.0.7.5-.x86_64-unknown-linux-gnu.zip
Extracting /home/ayushman/Downloads/sd.0.7.5-.x86_64-unknown-linux-gnu.zip
Installing to /home/ayushman/.local/opt/sd-v0.7.5/bin/sd
mv: cannot stat './sd-*/sd': No such file or directory
mv: cannot stat './sd*': No such file or directory

Then I manualy compiled files in sd-0.7.6. The sd command is contained  sd-0.7.6/target/debug . Actually the files in  sd-0.7.6 had to be build first. So i installed cargo , then performed cargo build , then found sd in sd-0.7.6/target/debug/ .
Then tried to change sd/install.sh https://github.com/chetak123/packages/blob/new_sd/sd/install.sh

But now it can't find /home/ayushman/Downloads/sd.0.7.5-.x86_64-unknown-linux-gnu.zip

**Comment by solderjs** [comment]
You're skipping ahead a bit.

When you run `node _webi/test.js sd/` it will output JSON with the download string. You should download that link to ~/Downloads/.

Then you should use `unzip` to unzip it and then use `lsd --tree ./path/to/sd` to see what's inside.

After that, then you can edit the path.

When you build it yourself you are getting a debug build, not the production build that is published.

Does that makes sense?

**Comment by coolaj86** [comment]
This is up on https://beta.webinstall.dev/sd and should go live at https://webinstall.dev/sd with some other updates tomorrow.

**Comment by chetak123** [comment]
Well thanks for merging my pull request, it's my first successful PR to an open source project

**Comment by coolaj86** [comment]
👍  You're welcome. Thanks for sticking with it and following through.

Normally it's not so convoluted with the `git rebase` and such, we just had a number of confilcts and redos on this that is atypical of a normal flow.

However, I'd recommend using an editor like VSCode or `vim` and some tools like `Prettier` and such so that your whitespace and formatting are consistent - that's one of the things I'll want to clean on this later.

Whitespace alignment is important for readability.
