### ISSUE TITLE
add `lsd`

### ISSUE THREAD

**Issue by solderjs** [webinstall/packages#54]
We want to add this as a cross-platform drop-in replacement for `ls` - because icons and highlighting are awesome

~~This may be tricky as it requires a nerd-font to be installed.~~
( we now have nerdfont https://webinstall.dev/nerdfont )

This could be as simple as copying `jq` or `rg` and changing a few things:

```
rsync -av jq/ lsd/
```

1. Official Releases are at https://github.com/Peltoche/lsd/releases
    - [ ] update `lsd/release.js` to use this repo
2. How does `lsd` unpack (i.e. as a single file? as a .tar.gz? as a .tar.gz with a folder named lsd?)
    - [ ] update `lsd/install.sh` following the example of either `jq` or `rg`
    - [ ] update `lsd/install.ps1` following the example of either `jq` or `rg`
3. Needs an updated tagline and cheat sheet
    - [ ] update `lsd/README.md`
        - [ ] official URL
        - [ ] tagline
        - [ ] Switch versions
        - [ ] description / summary
        - [ ] How to alias and escape the alias (see `bat`)
        - [ ] General pointers on usage (drop in replacement for ls)

## Skills required

- Basic Command Line knowledge (`mkdir`, `ls`, `tar`, `unzip`)

It's also okay to have multiple people work on part of this (i.e. the Cheat Sheet can be done independently from the `install.sh`)

**Comment by avats-dev** [comment]
**Hey @solderjs , I know command line but I don't know what I need to do here. Guide me.**
> I would love to contribute.

**Comment by solderjs** [comment]
Added in #80
