### ISSUE TITLE
problem with Postgres installer

### ISSUE THREAD

**Issue by dwoodwardgb** [webinstall/packages#55]
I believe there is a typo here 
<img width="671" alt="Screen Shot 2020-07-23 at 8 04 52 AM" src="https://user-images.githubusercontent.com/13407106/88284366-46fa9780-ccbb-11ea-8092-c50c59a054ec.png">
The url should read `postgres -D $HOME/.local/share/postgres/var -p 5432` instead

**Comment by solderjs** [comment]
Indeed, you are correct! Thank you for spotting that typo.

Would you like to PR and submit the fix?

The Cheat Sheet is here: https://github.com/webinstall/packages/blob/master/postgres/README.md

You can click Edit, make the necessary change, Commit Changes (it will create a "fork"), and then Pull Request.

After that I'll approve review and approve the change and publish.

**Comment by solderjs** [comment]
Closed by https://github.com/webinstall/packages/pull/56
