### ISSUE TITLE
suggestion for bat cheat sheet, bypass alias

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/packages#58]
a suggestion to add something to the bat cheat sheet

if you're aliasing cat to bat, it would be nice to teach folks the way to bypass the alias

```bash
\cat foo
```

**Comment by solderjs** [comment]
That's a good idea to add to the Alias section here: https://github.com/webinstall/packages/blob/master/bat/README.md

**Comment by solderjs** [comment]
@ryanburnette What's the wording you'd suggest for that? Something like this?

~~~
For situations in which you must use `cat` exactly, remember that you can escape the alias:

```bash
\cat foo
```

~~~

**Comment by ryanburnette** [comment]
Yea looks good.

For me, sometimes I use cat to then copy something to the clipboard, and bat gets in the way. I had to remind myself how to break out of an alias. I thought it might help others.

**Comment by solderjs** [comment]
Re-opening: I didn't review closely enough, this change should have gone in the section "How to alias as cat
"

**Comment by solderjs** [comment]
Live at https://webinstall.dev/bat
