### ISSUE TITLE
Show the download source when downloading.

### ISSUE THREAD

**Issue by solderjs** [webinstall/packages#63]
Currently we show were a download will be downloaded:

```txt
Downloading node to /Users/aj/Downloads/node-v14.7.0-darwin-x64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30.2M  100 30.2M    0     0   879k      0  0:00:35  0:00:35 --:--:--  987k
```

To increase transparency and trust, it may be good to show where the download is coming from:

```txt
Downloading https://nodejs.org/dist/v12.18.3/node-v12.18.3-darwin-x64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30.2M  100 30.2M    0     0   879k      0  0:00:35  0:00:35 --:--:--  987k

Saved node to /Users/aj/Downloads/node-v12.18.3-darwin-x64.tar.gz
```

Two things that need to be solved for here:

- [ ] How can we show (potentially long) URLs in a friendly way?
- [ ] Update the `webi_download` function `_webi/template.sh` with the new wording

## Skills required

- Visual / Verbal Communication
- Basic Command Line knowledge (`mkdir`, `ls`, `tar`, `unzip`)

It's fine for the display to be brainstormed by one person and the implementation to be done by another. However, this is probably basic enough for anyone with minimal bash experience to make the change.

**Comment by yollotltamayo** [comment]
Hello this is my idea for the friendly URLs , show _package_ name and then _download source_ , the URL could be a direct link to the page, also i can implement it , let me know your opinion .
----------------------------------------------------------------------------------------------------------------------------------
 ```
 Downloading node from https://nodejs.org/dist/v12.18.3/node-v12.18.3-darwin-x64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30.2M  100 30.2M    0     0   879k      0  0:00:35  0:00:35 --:--:--  987k

Saved node to /Users/aj/Downloads/node-v12.18.3-darwin-x64.tar.gz
```

**Comment by solderjs** [comment]
Sounds good to me.

Here's another thought:

```txt
Downloading node from
https://nodejs.org/dist/v12.18.3/node-v12.18.3-darwin-x64.tar.gz
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed
100 30.2M  100 30.2M    0     0   879k      0  0:00:35  0:00:35 --:--:--  987k

Saved as /Users/aj/Downloads/node-v12.18.3-darwin-x64.tar.gz
```

- Put the URL on its own line (no sure if this looks better or worse... these URLs can be long)
- Remove redundant package name from "Saved as"

I'm also fine with your proposal as-is. Go ahead and make the change as you think best. 👍

**Comment by yollotltamayo** [comment]
Just made the PR,let me know the feedback.
