### ISSUE TITLE
correct Prettier cheat sheet about `--ignore`

### ISSUE THREAD

**Issue by solderjs** [webinstall/packages#69]
As seen on https://webinstall.dev/prettier/ the Prettier cheat sheet, the `--ignore` option is incorrect.

- `--ignore` is not the correct argument to pass names of directories to ignore
- need to lookup in prettier docs the correct flag name (if any), or remove

Also, the format of `.prettierignore` is incorrect.

- paths should not begin with `./`, they should be left bare
- `./dist` should be `dist/`

Needs to be edited here: https://github.com/webinstall/packages/blob/master/prettier/README.md

**Comment by ctyin** [comment]
First timer here: could I be assigned this?

**Comment by solderjs** [comment]
Thanks! We'll merge this in today.
