### ISSUE TITLE
root path

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/packages#73]
Maybe this should be documented. Maybe it could be improved. Forgive my bad memory and poor search technique, this may be a duplicate.

I'm often in Linux as user ryan, and need to do things as root through sudo. Here is an example.

```bash
sudo $(which serviceman) add $(which caddy) run
```

I make it work using `$()`.

If this is a good thing, perhaps it should be documented.

If there's a better way, enlighten me.

**Comment by ryanburnette** [comment]
Listing root services.

```bash
sudo $(which serviceman) list
```

**Comment by solderjs** [comment]
It’s on the page already.

sudo env PATH=“$PATH” ...

**Comment by ryanburnette** [comment]
Is that something you run once and problem solved?

**Comment by solderjs** [comment]
Every time.

You’d have to install it as root to put it in root’s PATH permanently.

**Comment by solderjs** [comment]
See https://webinstall.dev/serviceman/

**Comment by ryanburnette** [comment]
I tried...

```bash
$ sudo su
$ curl https://webinstall.dev/pathman | bash
$ webi serviceman
```


```bash
$ sudo serviceman list
sudo: serviceman: command not found
```

**Comment by solderjs** [comment]
Probably because the .bashrc is never executed because `sudo` is putting it in “non-interactive” mode.

This is one of those Linux issues that has no good cross-distro solution.

**Comment by solderjs** [comment]
Also, you installed pathman, bot serviceman.

**Comment by ryanburnette** [comment]
I installed both. I always install pathman first so I get pathman and webi. Then I installed serviceman with webi.

**Comment by solderjs** [comment]
You could edit root’s .bashrc or .profile by hand to source .config/envman/PATH.env before the interactive check.

**Comment by solderjs** [comment]
I think the best solution is “sudo env PATH=$PATH ...”, but the “$(which ...)” works too.
