### ISSUE TITLE
Add string `exe` to array of testable extensions

### ISSUE THREAD

**Issue by solderjs** [webinstall/packages#89]
A while back the main releases code was updated to allow for bare `.exe` and `bin` installs, but the test code had not been updated.

We need to add `exe` to the beginning of this list:

https://github.com/webinstall/packages/blob/72406c4e0d438b76da054be8d5eff42d08312498/_webi/test.js#L69

**Comment by Akshansh99** [comment]
Hello I'm Akshansh. I want to contribute to this problem.

**Comment by Akshansh99** [comment]
I have updated the formats array with `exe` in formats array. I've created a pull request #90 for it.

**Comment by solderjs** [comment]
Thank you. Merged in #91
