### ISSUE TITLE
[Installer] Add caddy install script for Windows 10

### ISSUE THREAD

**Issue by coolaj86** [webinstall/packages#93]
# Add caddy for Windows 10

We've got a caddy installer for Mac and Linux ( https://webinstall.dev/caddy ), but we need to add one for Windows 10

This could be as simple as copying `_example/install.ps1` to `caddy/install.ps1`, and updating the name and install path according to the comment in the example about standalone binary.

# How to create a webi installer

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, variables)

## Steps

NOT exactly the same as the video!! (but close)

1. `cp _examples/install.ps1 caddy/`
2. Find and replace the strings `foobar` and `foo` in `caddy/install.ps1` with `caddy`.
3. Read the comment in `caddy/install.ps1` about SINGLE BINARY
    - uncomment path for single binary
    - delete path intended for directory (explained in the video) 
4. Test that the installer works
    - Run `node _webi/test.js caddy/`
    - Check `caddy/install.ps1` and then run `powershell -ExecutionPolicy Bypass caddy/install.ps1`

**Comment by NorbertLuszkiewicz** [comment]
Hey I would love to tackle this one

**Comment by anshdhinhgra47** [comment]
Can I also take part in it ?

**Comment by coolaj86** [comment]
@anshdhinhgra47 Take a look at where Norbert left off and see what you can do:
https://github.com/webinstall/packages/pull/94

**Comment by anshdhinhgra47** [comment]
Alright! Thank you :)

**Comment by coolaj86** [comment]
@anshdhinhgra47 @NorbertLuszkiewicz Are either of you working on this?

Just needs a few corrections: https://github.com/webinstall/packages/pull/94/files

**Comment by coolaj86** [comment]
This became time sensitive and I haven't heard back from either of you, so I tested, fixed, and PRed.
