### ISSUE TITLE
[Feat] Add test and temp files to .gitignore

### ISSUE THREAD

**Issue by coolaj86** [webinstall/packages#96]
When you run `node _webi/test.js XXXX/` it creates the following:

- install-XXXX.sh
- install-XXXX.ps1

A couple of people have created PRs that have these junk files in them by mistake.

Adding patterns that match (only) these files to `.gitignore` will solve this problem. I think that these patterns should do the trick:
- `install-*.sh`
- `install-*.ps1`

Also, when someone is working in vim it creates a swap files like these:
- `.install.sh.swp`
- `.install.sh.swo` 

We should also add a pattern to match (only) those files.

**Comment by raj5036** [comment]
Hi @solderjs 
Can I start working on this  ?

**Comment by coolaj86** [comment]
@raj5036 Someone else already had this in PR.

**Comment by coolaj86** [comment]
@raj5036 How are your `bash` skills? There's another issue that may need some help.
