### ISSUE TITLE
[Bug] Add -Force argument to all .ps1 scripts that call New-Item

### ISSUE THREAD

**Issue by coolaj86** [webinstall/packages#99]
This will make the calls to `New-Item` equivalent of `mkdir -p`.

- Every instance of `New-Item` throughout the `.ps1` scripts should use `-Force`.
- No instance of `New-Item` should use `-ErrorAction Ignore` (`-Force` does this, but only for Exists errors)

This is what the `New-Item` usages look like:

https://github.com/webinstall/packages/blob/master/nerdfont/install.ps1#L6

# Skills Required

- Editor w/ Find & Replace
  - Anyone could quickly do this with a text like VSCode that supports recursive find & replace

Or

- Command line
  - This would take seconds using [rg](https://webinstall.dev/rg) (modern grep) and [sd](https://webinstall.dev/sd) (modern sed)

**Comment by Pratyush-Saxena** [comment]
@coolaj86 can i work on this issue

**Comment by coolaj86** [comment]
Yes, this should be a pretty simple update. Go ahead.

**Comment by Pratyush-Saxena** [comment]
@coolaj86 i have created a pr #102  pls have a look
